# Generated by Django 5.1.4 on 2025-01-09 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('razorpaybackend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transcation',
            new_name='Transacation',
        ),
    ]
